"""add_tie_breaking_fields_to_users

Revision ID: 0006_add_tie_breaking_fields
Revises: 0005_seed_bets
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006_add_tie_breaking_fields'
down_revision = '0005_seed_bets'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('correct_results', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('lone_wolf_victories', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('defeats', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'defeats')
    op.drop_column('users', 'lone_wolf_victories')
    op.drop_column('users', 'correct_results')
    # ### end Alembic commands ###
